ec2_address = "ec2-34-219-173-229.us-west-2.compute.amazonaws.com"
user = "ec2-user"
key_file = "/.ssh/bpchivers_oregon.pem"
git_repo_owner = "MSDS698"
git_repo_name = "whatrthose"
git_user_id = "bpchivers"
