ec2_address = "ec2-34-219-157-101.us-west-2.compute.amazonaws.com"
user = "ec2-user"
key_file = "/Dropbox/licenses/ttishihara-msan692-oregon.pem"
git_repo_owner = "MSDS698"
git_repo_name = "whatrthose"
git_user_id = "ttishihara"
